"""empty message

Revision ID: 9b28d783fddb
Revises: 0fc943787671
Create Date: 2022-08-30 18:03:36.986358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b28d783fddb'
down_revision = '0fc943787671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demographics', sa.Column('autism_exp', sa.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demographics', 'autism_exp')
    # ### end Alembic commands ###
