"""empty message

Revision ID: a63886db8c05
Revises: de2e0fbe5c19
Create Date: 2022-09-11 11:18:53.680310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63886db8c05'
down_revision = 'de2e0fbe5c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trials', sa.Column('keypress_time', sa.VARCHAR(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trials', 'keypress_time')
    # ### end Alembic commands ###
