"""empty message

Revision ID: ae665f62ed8f
Revises: 331668dcae09
Create Date: 2022-09-06 16:46:56.248656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae665f62ed8f'
down_revision = '331668dcae09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('completion_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'completion_time')
    # ### end Alembic commands ###
