"""empty message

Revision ID: de2e0fbe5c19
Revises: ae665f62ed8f
Create Date: 2022-09-10 14:31:16.572948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2e0fbe5c19'
down_revision = 'ae665f62ed8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('recaptcha_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'recaptcha_complete')
    # ### end Alembic commands ###
